// <auto-generated />
namespace Bookshelf.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20171026AddedMinandMaxLengthdataannotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20171026AddedMinandMaxLengthdataannotations));
        
        string IMigrationMetadata.Id
        {
            get { return "201710261424127_20171026 Added Min and Max Length data annotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
